export default  {
    1: 'VALIDATE_OK',
    2: 'INVALID_ADDRESS',
    3: 'NEGATIVE_AMOUNT',
    4: 'NEGATIVE_FEE',
    5: 'NO_BALANCE',
    6: 'INVALID_REFERENCE',
    7: 'INVALID_NAME_LENGTH',
    8: 'INVALID_VALUE_LENGTH',
    9: 'NAME_ALREADY_REGISTRED',
    15: 'INVALID_AMOUNT',
    17: 'NAME_NOT_LOWER_CASE',
    27: 'INVALID_DATA_LENGTH',
    34: 'INVALID_PAYMENTS_LENGTH',
    40: 'FEE_LESS_REQUIRED',
    41: 'INVALID_RAW_DATA',
    1000: 'NOT_YET_RELEASED'
};
